services:
  orvrm:
    image: ghcr.io/maartenbode/orvrm:latest
    ports:
      - "8080:8080"
    environment:
      - OSRM_URL=http://osrm:5000
    depends_on:
      - osrm
    restart: unless-stopped

  osrm:
    image: osrm/osrm-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data:/data
    command: "osrm-routed --algorithm mld /data/netherlands-latest.osrm"
    restart: unless-stopped
